const rsData = [
  {
    "no": 1,
    "name": "RSU Muhammadiyah Sumatera Utara",
    "email": "rsumuhammadiyahsumut27@gmail.com",
    "code": "1275885",
    "rsoName": "RS Umum Muhammadiyah Sumatera Utara",
    "class": "D",
    "city": "Kota Medan",
    "prov": "SUMATERA UTARA",
    "inOj": true,
    "cases": 26461
  },
  {
    "no": 2,
    "name": "RSU ‘Aisyiyah Padang",
    "email": "rsuaisyiyahpadang@gmail.com",
    "code": "1371112",
    "rsoName": "RS Umum Aisyiyah Padang",
    "class": "C",
    "city": "Kota Padang",
    "prov": "SUMATERA BARAT",
    "inOj": true,
    "cases": 11565
  },
  {
    "no": 3,
    "name": "RS ‘Aisyiyah Pariaman",
    "email": "rsapariaman@yahoo.co.id",
    "code": "1306050",
    "rsoName": "-",
    "class": "-",
    "city": "-",
    "prov": "-",
    "inOj": false,
    "cases": 0
  },
  {
    "no": 4,
    "name": "RS Muhammadiyah Palembang",
    "email": "rsmuh_plg@yahoo.co.id",
    "code": "1671301",
    "rsoName": "RS Muhammadiyah Palembang",
    "class": "C",
    "city": "Kota Palembang",
    "prov": "SUMATERA SELATAN",
    "inOj": true,
    "cases": 61469
  },
  {
    "no": 5,
    "name": "RSU Muhammadiyah Metro",
    "email": "info.rsumm@gmail.com",
    "code": "1872031",
    "rsoName": "RS Umum Islam Metro",
    "class": "D",
    "city": "Kota Metro",
    "prov": "LAMPUNG",
    "inOj": true,
    "cases": 18253
  },
  {
    "no": 6,
    "name": "RSIA PKU Muhammadiyah Cipondoh Kota Tangerang",
    "email": "rspkumcipondoh@gmail.com",
    "code": "3671218",
    "rsoName": "RS Ibu dan Anak PKU Muhammadiyah Cipondoh",
    "class": "C",
    "city": "Kota Tangerang",
    "prov": "BANTEN",
    "inOj": true,
    "cases": 8320
  },
  {
    "no": 7,
    "name": "RS Islam Jakarta Cempaka Putih",
    "email": "rsijpusat@rsi.co.id",
    "code": "3173036",
    "rsoName": "RS Umum AL Dr. Mintohardjo",
    "class": "B",
    "city": "Kota Jakarta Pusat",
    "prov": "DKI JAKARTA",
    "inOj": true,
    "cases": 46680
  },
  {
    "no": 8,
    "name": "RS Islam Jakarta Pondok Kopi",
    "email": "rsijpk@rsijpondokkopi.co.id",
    "code": "3172505",
    "rsoName": "RS Islam Jakarta Pondok Kopi",
    "class": "B",
    "city": "Kota Jakarta Timur",
    "prov": "DKI JAKARTA",
    "inOj": true,
    "cases": 118486
  },
  {
    "no": 9,
    "name": "RS Islam Jakarta Sukapura Kelapa Gading",
    "email": "rsijsukapura@gmail.com",
    "code": "3175326",
    "rsoName": "RS Islam Jakarta Sukapura",
    "class": "C",
    "city": "Kota Jakarta Utara",
    "prov": "DKI JAKARTA",
    "inOj": true,
    "cases": 113179
  },
  {
    "no": 10,
    "name": "RS Jiwa Islam Klender",
    "email": "rsjiwaislam@yahoo.co.id / sekretariatrsjik@gmail.com",
    "code": "3172735",
    "rsoName": "RS Jiwa Islam Klender",
    "class": "C",
    "city": "Kota Jakarta Timur",
    "prov": "DKI JAKARTA",
    "inOj": true,
    "cases": 25448
  },
  {
    "no": 11,
    "name": "RSU Muhammadiyah Taman Puring",
    "email": "rsmtp@rsmtp.co.id / sekretariat@rsmtp.co.id / sdi@rsmtp.co.id",
    "code": "3171781",
    "rsoName": "RS Muhammadiyah Taman Puring",
    "class": "C",
    "city": "Kota Jakarta Selatan",
    "prov": "DKI JAKARTA",
    "inOj": true,
    "cases": 37844
  },
  {
    "no": 12,
    "name": "RS Muhammadiyah Bandung",
    "email": "rsmuhammadiyahbandung53@yahoo.co.id",
    "code": "3273106",
    "rsoName": "RS Umum Muhammadiyah",
    "class": "C",
    "city": "Kota Bandung",
    "prov": "JAWA BARAT",
    "inOj": true,
    "cases": 59502
  },
  {
    "no": 13,
    "name": "RS Islam Zam Zam Muhammadiyah Jatibarang",
    "email": "rsizjtbimy@yahoo.co.id / rspkujtb@gmail.com",
    "code": "3212055",
    "rsoName": "RS Umum Pertamina Balongan Indramayu",
    "class": "D",
    "city": "Indramayu",
    "prov": "JAWA BARAT",
    "inOj": true,
    "cases": 4705
  },
  {
    "no": 14,
    "name": "RS Muhammadiyah Cirebon",
    "email": "rsumuhammadiyahcrb@gmail.com / muhammadiyah.hospital@yahoo.com",
    "code": "3274111",
    "rsoName": "RS Umum Muhammadiyah",
    "class": "D",
    "city": "Kota Cirebon",
    "prov": "JAWA BARAT",
    "inOj": true,
    "cases": 2373
  },
  {
    "no": 15,
    "name": "RSU Universitas Muhammadiyah Cirebon",
    "email": "rstmumc@gmail.com / rsuumc@rsu-umc.com",
    "code": "3209052",
    "rsoName": "RS Umum Universitas Muhammadiyah Cirebon",
    "class": "C",
    "city": "Cirebon",
    "prov": "JAWA BARAT",
    "inOj": true,
    "cases": 37460
  },
  {
    "no": 16,
    "name": "RS Muhammadiyah Bandung Selatan",
    "email": "rsmbandungselatan@gmail.com",
    "code": "3204169",
    "rsoName": "RS Muhammadiyah Bandung Selatan",
    "class": "D",
    "city": "Bandung",
    "prov": "JAWA BARAT",
    "inOj": true,
    "cases": 27879
  },
  {
    "no": 17,
    "name": "RS Roemani Muhammadiyah Semarang",
    "email": "rs_roemani@yahoo.co.id",
    "code": "3374080",
    "rsoName": "RS Roemani Muhammadiyah Semarang",
    "class": "C",
    "city": "Kota Semarang",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 111336
  },
  {
    "no": 18,
    "name": "RS PKU Muhammadiyah Surakarta",
    "email": "humas_pkusolo@yahoo.co.id / pkumuhammadiyahsolo@gmail.com",
    "code": "3372096",
    "rsoName": "RS PKU Muhammadiyah Surakarta",
    "class": "B",
    "city": "Kota Surakarta",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 111347
  },
  {
    "no": 19,
    "name": "RS PKU Muhammadiyah Delanggu",
    "email": "humas@pku-delanggu.com / info@pku-delanggu.com / sekretariat@pku-delanggu.com",
    "code": "3310416",
    "rsoName": "RS Umum PKU Muhammadiyah Delanggu",
    "class": "C",
    "city": "Klaten",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 72436
  },
  {
    "no": 20,
    "name": "RS PKU Muhammadiyah Temanggung",
    "email": "tmg.rspku@gmail.com",
    "code": "3323050",
    "rsoName": "RS PKU Muhammadiyah Temanggung",
    "class": "C",
    "city": "Temanggung",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 57369
  },
  {
    "no": 21,
    "name": "RS PKU Muhammadiyah Sruweng",
    "email": "rsmuhammadiyahsruweng@yahoo.co.id",
    "code": "3305103",
    "rsoName": "RS Umum PKU Muhammadiyah Sruweng",
    "class": "C",
    "city": "Kebumen",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 73260
  },
  {
    "no": 22,
    "name": "RS PKU Muhammadiyah Mayong-Jepara",
    "email": "rspkumuhammadiyah77@yahoo.com",
    "code": "3320089",
    "rsoName": "RS Umum PKU Muhammadiyah Mayong",
    "class": "C",
    "city": "Jepara",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 77929
  },
  {
    "no": 23,
    "name": "RS PKU Muhammadiyah Karanganyar",
    "email": "rspkumuhammadiyah@yahoo.com",
    "code": "3313033",
    "rsoName": "RS PKU Muhammadiyah Karanganyar",
    "class": "C",
    "city": "Karanganyar",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 105186
  },
  {
    "no": 24,
    "name": "RS PKU Muhammadiyah Cepu",
    "email": "rspku_cepu@yahoo.co.id",
    "code": "3316051",
    "rsoName": "RS Umum PKU Muhammadiyah Cepu",
    "class": "C",
    "city": "Blora",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 57056
  },
  {
    "no": 25,
    "name": "RS PKU Muhammadiyah Gombong",
    "email": "admin.rs@pkugombong.com / rspkumuhammadiyahgb@gmail.com",
    "code": "3305066",
    "rsoName": "RS Umum PKU Muhamadiyah Gombong",
    "class": "B",
    "city": "Kebumen",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 166220
  },
  {
    "no": 26,
    "name": "RSU PKU ‘Aisyiyah Boyolali",
    "email": "rspkuaboy@yahoo.co.id",
    "code": "3309063",
    "rsoName": "RS Umum PKU Aisyiyah Boyolali",
    "class": "C",
    "city": "Boyolali",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 52815
  },
  {
    "no": 27,
    "name": "RS Muhammadiyah Selogiri-Wonogiri",
    "email": "muhammadiyahwonogiri@yahoo.co.id / rsmuhammadiyahselogiri@gmail.com",
    "code": "3312284",
    "rsoName": "RS Umum Muhammadiyah Selogiri",
    "class": "D",
    "city": "Wonogiri",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 32275
  },
  {
    "no": 28,
    "name": "RSU PKU Muhammadiyah Gubug Grobogan",
    "email": "rsmgbg@yahoo.co.id / rsmgbg@yahoo.com",
    "code": "3315059",
    "rsoName": "RS Umum Islam Purwodadi",
    "class": "D",
    "city": "Grobogan",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 14979
  },
  {
    "no": 29,
    "name": "RSU Muhammadiyah Siti Aminah-Bumiayu",
    "email": "rsm.sitiaminah@gmail.com / rsm.sitiaminah@yahoo.com",
    "code": "3329056",
    "rsoName": "RS Umum Muhammadiyah Siti Aminah",
    "class": "C",
    "city": "Brebes",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 87303
  },
  {
    "no": 30,
    "name": "RS Islam PKU Muhammadiyah Tegal",
    "email": "rsi_muhtegal@ymail.com / rsi_muhtegal@gmail.com",
    "code": "3328055",
    "rsoName": "RSI PKU Muhammadiyah Tegal",
    "class": "C",
    "city": "Tegal",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 136696
  },
  {
    "no": 31,
    "name": "RS Islam PKU Muhammadiyah Pekajangan",
    "email": "rsi.pekajangan@yahoo.co.id / info@rsipekajangan.com",
    "code": "3326016",
    "rsoName": "RS Islam PKU Muhammadiyah Pekajangan",
    "class": "C",
    "city": "Pekalongan",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 93439
  },
  {
    "no": 32,
    "name": "RS Muhammadiyah Rodliyah Achid Moga",
    "email": "rsmrodliyahachid@gmail.com / rsmuhammadiyahmoga@gmail.com",
    "code": "3327032",
    "rsoName": "RS Muhammadiyah Rodliyah Achid",
    "class": "D",
    "city": "Pemalang",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 24785
  },
  {
    "no": 33,
    "name": "RS Islam Kendal",
    "email": "rsimuhkendal@yahoo.co.id / rsi.kendal@gmail.com",
    "code": "3324036",
    "rsoName": "RS Umum Islam Kendal",
    "class": "C",
    "city": "Kendal",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 130835
  },
  {
    "no": 34,
    "name": "RSIA ‘Aisyiyah Klaten",
    "email": "rsia.klt@gmail.com",
    "code": "3310405",
    "rsoName": "RS Umum Diponegoro Dua Satu Klaten",
    "class": "C",
    "city": "Klaten",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 51210
  },
  {
    "no": 35,
    "name": "RSU Muhammadiyah Darul Istiqomah Kaliwungu Kendal",
    "email": "rsdimuhammadiyah@yahoo.com",
    "code": "3324037",
    "rsoName": "RS Umum Muhammadiyah Darul Istiqomah Kendal",
    "class": "D",
    "city": "Kendal",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 41028
  },
  {
    "no": 36,
    "name": "RS ‘Aisyiyah Kudus",
    "email": "rsa_kudus@yahoo.com",
    "code": "3319021",
    "rsoName": "RS Aisyiyah Kudus",
    "class": "C",
    "city": "Kudus",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 69569
  },
  {
    "no": 37,
    "name": "RS ‘Aisyiyah Muntilan",
    "email": "rsia.muntilan@gmail.com / rsiamuntilan@gmail.com / rsa.muntilan@gmail.com",
    "code": "3308017",
    "rsoName": "RS Umum Aisyiyah Muntilan",
    "class": "C",
    "city": "Magelang",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 54793
  },
  {
    "no": 38,
    "name": "RS PKU Muhammadiyah Sragen",
    "email": "pkum_sragen@yahoo.com",
    "code": "3314090",
    "rsoName": "RS Umum PKU Muhammadiyah Sragen",
    "class": "C",
    "city": "Sragen",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 25619
  },
  {
    "no": 39,
    "name": "RSU Fastabiq Sehat PKU Muhammadiyah Pati",
    "email": "rsfastabiqsehat@gmail.com",
    "code": "3318108",
    "rsoName": "RS Umum Keluarga Sehat",
    "class": "C",
    "city": "Pati",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 144577
  },
  {
    "no": 40,
    "name": "RS PKU Muhammadiyah Petanahan",
    "email": "rspkupetanahan@yahoo.com",
    "code": "3305117",
    "rsoName": "RS Umum PKU Muhammadiyah Petanahan Kebumen",
    "class": "D",
    "city": "Kebumen",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 23499
  },
  {
    "no": 41,
    "name": "RS PKU Muhammadiyah Wonosobo",
    "email": "pkuwsb@gmail.com / pkuwsb@yahoo.co.id",
    "code": "3307051",
    "rsoName": "RS Umum  PKU Muhammadiyah Wonosobo",
    "class": "C",
    "city": "Wonosobo",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 78456
  },
  {
    "no": 42,
    "name": "RS PKU Muhammadiyah Kartasura",
    "email": "pkumuhammadiyahkartasura@yahoo.com",
    "code": "3311230",
    "rsoName": "RS PKU Muhammadiyah Kartasura",
    "class": "D",
    "city": "Sukoharjo",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 2681
  },
  {
    "no": 43,
    "name": "RSU PKU Muhammadiyah Sukoharjo",
    "email": "pku.sukoharjo@gmail.com",
    "code": "3311225",
    "rsoName": "RS Umum PKU Muhammadiyah Sukoharjo",
    "class": "C",
    "city": "Sukoharjo",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 48407
  },
  {
    "no": 44,
    "name": "RSU ‘Aisyiyah Purworejo",
    "email": "rsiaa_pwr@yahoo.com",
    "code": "3306023",
    "rsoName": "RS Umum  Aisyiyah",
    "class": "D",
    "city": "Purworejo",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 5752
  },
  {
    "no": 45,
    "name": "RS PKU Muhammadiyah Blora",
    "email": "rsmuhblora@yahoo.co.id / rsmuhblora@gmail.com",
    "code": "3316063",
    "rsoName": "RS Umum PKU Muhammadiyah Blora",
    "class": "D",
    "city": "Blora",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 21751
  },
  {
    "no": 46,
    "name": "RS Muhammadiyah Mardhatillah Randudongkal",
    "email": "rsmuhmardhatillah@gmail.com",
    "code": "3327047",
    "rsoName": "RS Umum Muhammadiyah Mardhatillah",
    "class": "D",
    "city": "Pemalang",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 48328
  },
  {
    "no": 47,
    "name": "RSU PKU Muhammadiyah Jatinom Klaten",
    "email": "pkumuhammadiyah_jtn@yahoo.co.id",
    "code": "3310418",
    "rsoName": "RS Umum PKU Muhammadiyah Jatinom",
    "class": "C",
    "city": "Klaten",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 49281
  },
  {
    "no": 48,
    "name": "RS PKU ‘Aisyiyah Jepara",
    "email": "sitikhadijahjpr@yahoo.com",
    "code": "3320046",
    "rsoName": "RS PKU Aisyiyah Jepara",
    "class": "D",
    "city": "Jepara",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 12221
  },
  {
    "no": 49,
    "name": "RS PKU Muhammadiyah Kutowinangun",
    "email": "pkukuto@yahoo.co.id / pkukuto@gmail.com",
    "code": "3305118",
    "rsoName": "RS Umum PKU Muhammadiyah Kutowinangun",
    "class": "D",
    "city": "Kebumen",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 27047
  },
  {
    "no": 50,
    "name": "RSIA ‘Aisyiyah Pekajangan Pekalongan",
    "email": "rba610@gmail.com / rsi.pekajangan@yahoo.co.id",
    "code": "3326051",
    "rsoName": "RS Ibu dan Anak Aisyiyah Pekajangan Pekalongan",
    "class": "C",
    "city": "Pekalongan",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 7477
  },
  {
    "no": 51,
    "name": "RSGM Universitas Muhammadiyah Semarang",
    "email": "rsgm@unimus.ac.id",
    "code": "3374373",
    "rsoName": "RS Gigi dan Mulut Unimus",
    "class": "C",
    "city": "Kota Semarang",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 7665
  },
  {
    "no": 52,
    "name": "RSGM Soelastri Universitas Muhammadiyah Surakarta",
    "email": "rsgmsoelastri@ums.ac.id",
    "code": "3372239",
    "rsoName": "RS Gigi dan Mulut Soelastri",
    "class": "C",
    "city": "Kota Surakarta",
    "prov": "JAWA TENGAH",
    "inOj": false,
    "cases": 0
  },
  {
    "no": 53,
    "name": "RS PKU Muhammadiyah Sampangan Surakarta",
    "email": "pkusampangan@gmail.com",
    "code": "3372238",
    "rsoName": "RS PKU Muhammadiyah Sampangan Surakarta",
    "class": "D",
    "city": "Kota Surakarta",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 21639
  },
  {
    "no": 54,
    "name": "RS PKU Muhammadiyah Pedan Klaten",
    "email": "rsupkumuhpedan@gmail.com",
    "code": "3310425",
    "rsoName": "RS Umum PKU Muhammadiyah Pedan",
    "class": "D",
    "city": "Klaten",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 18583
  },
  {
    "no": 55,
    "name": "RS PKU Muhammadiyah Wonogiri",
    "email": "pkumuhammadiyah30@gmail.com / rspkuwngkota@gmail.com",
    "code": "3312316",
    "rsoName": "-",
    "class": "-",
    "city": "-",
    "prov": "-",
    "inOj": false,
    "cases": 0
  },
  {
    "no": 56,
    "name": "RS Islam Purwokerto",
    "email": "info@rsipurwokerto.co.id / rsislam.purwokerto@gmail.com",
    "code": "3302132",
    "rsoName": "RS Umum Islam Purwokerto",
    "class": "C",
    "city": "Banyumas",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 48599
  },
  {
    "no": 57,
    "name": "RSU PKU Muhammadiyah Banjarnegara",
    "email": "rsupkumuhammadiyah.bna@gmail.com",
    "code": "3304035",
    "rsoName": "RS Umum PKU Muhammadiyah Banjarnegara",
    "class": "D",
    "city": "Banjarnegara",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 13852
  },
  {
    "no": 58,
    "name": "RS PKU Muhammadiyah Purbalingga",
    "email": "pkum_pbg@yahoo.com",
    "code": "3303102",
    "rsoName": "RS Umum PKU Muhammadiyah Purbalingga",
    "class": "D",
    "city": "Purbalingga",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 15706
  },
  {
    "no": 59,
    "name": "RS Hj. Fatimah Sulhan PKU Muhammadiyah Demak",
    "email": "rspkumudemak@gmail.com",
    "code": "3321036",
    "rsoName": "RS Hj. Fatimah Sulhan PKU Muhammadiyah Demak",
    "class": "D",
    "city": "Demak",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 5476
  },
  {
    "no": 60,
    "name": "RS PKU Muhammadiyah Boja Kendal",
    "email": "rspkumuhammadiyahboja@gmail.com",
    "code": "3324053",
    "rsoName": "RS PKU Muhammadiyah Boja",
    "class": "D",
    "city": "Kendal",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 8196
  },
  {
    "no": 61,
    "name": "RS PKU ‘Aisyiyah Kota Kendal",
    "email": "rspkuaisyiyahkendal@gmail.com",
    "code": "3324052",
    "rsoName": "RS PKU Aisyiyah Kendal",
    "class": "D",
    "city": "Kendal",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 10562
  },
  {
    "no": 62,
    "name": "RSU Amanah Muhammadiyah Sumpiuh Banyumas",
    "email": "rsiaamanahsumpiuh@gmail.com",
    "code": "3302121",
    "rsoName": "RS Umum PKU Muhammadiyah Amanah Sumpiuh",
    "class": "C",
    "city": "Banyumas",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 36013
  },
  {
    "no": 63,
    "name": "RSU PKU Muhammadiyah Prambanan",
    "email": "rspkum.prambanan@gmail.com",
    "code": "3310426",
    "rsoName": "RS PKU Muhammadiyah Prambanan",
    "class": "D",
    "city": "Klaten",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 17332
  },
  {
    "no": 64,
    "name": "RS PKU Muhammadiyah Pamotan",
    "email": "rspku_muhpa@yahoo.com",
    "code": "3317038",
    "rsoName": "RS PKU Muhammadiyah Pamotan",
    "class": "C",
    "city": "Rembang",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 11476
  },
  {
    "no": 65,
    "name": "RSU PKU Dr. Soemowidagdo Boyolali",
    "email": "rsupkudrsoemowidagdo@gmail.com",
    "code": "3309149",
    "rsoName": "RS Umum PKU dr. Soemowidagdo Boyolali",
    "class": "D",
    "city": "Boyolali",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 1440
  },
  {
    "no": 66,
    "name": "RS Sarkies ‘Aisyiyah Kudus",
    "email": "rssarkies@gmail.com",
    "code": "3319113",
    "rsoName": "RS Sarkies 'Aisyiyah Kudus",
    "class": "C",
    "city": "Kudus",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 47169
  },
  {
    "no": 67,
    "name": "RSU Aghisna Medika Kroya Cilacap",
    "email": "pkuaghisnakroya@gmail.com",
    "code": "3301108",
    "rsoName": "RS Umum PKU Muhammdiyah Aghisna Kroya",
    "class": "C",
    "city": "Cilacap",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 38028
  },
  {
    "no": 68,
    "name": "RS Aghisna Medika Sidareja",
    "email": "rsaghisna.sidareja@gmail.com",
    "code": "3301114",
    "rsoName": "RS Umum Aghisna Medika Sidareja",
    "class": "D",
    "city": "Cilacap",
    "prov": "JAWA TENGAH",
    "inOj": true,
    "cases": 28053
  },
  {
    "no": 69,
    "name": "RSU PKU Muhammadiyah AR Fachrudin Salatiga",
    "email": "–",
    "code": "3373092",
    "rsoName": "RS Ibu dan Anak Hermina Mutiara Bunda",
    "class": "C",
    "city": "Kota Salatiga",
    "prov": "JAWA TENGAH",
    "inOj": false,
    "cases": 0
  },
  {
    "no": 70,
    "name": "RS Islam Muhammadiyah 2 Kendal",
    "email": "rsim2kendal@gmail.com",
    "code": "3324054",
    "rsoName": "RSI MUHAMMADIYAH 2 KENDAL",
    "class": "D",
    "city": "Kendal",
    "prov": "JAWA TENGAH",
    "inOj": false,
    "cases": 0
  },
  {
    "no": 71,
    "name": "RS Muhammadiyah Ahmad Dahlan Kota Kediri",
    "email": "rsmad.kotakediri@yahoo.com",
    "code": "3571122",
    "rsoName": "RS Muhammadiyah Ahmad Dahlan",
    "class": "C",
    "city": "Kota Kediri",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 46387
  },
  {
    "no": 72,
    "name": "RSU Muhammadiyah Surya Melati",
    "email": "surya.melati@yahoo.co.id",
    "code": "3506047",
    "rsoName": "RS Umum Muhammadiyah Surya Melati",
    "class": "D",
    "city": "Kediri",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 4680
  },
  {
    "no": 73,
    "name": "RSI Aminah Blitar",
    "email": "rsiaminahblitar@gmail.com",
    "code": "3572073",
    "rsoName": "RS Islam Aminah",
    "class": "C",
    "city": "Kota Blitar",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 18503
  },
  {
    "no": 74,
    "name": "RSU Aminah Blitar",
    "email": "rsua_aminah@yahoo.co.id / rsuaminah.blitar39@gmail.com / rsua_blitar@yahoo.co.id",
    "code": "3572065",
    "rsoName": "RS Umum Aminah Blitar",
    "class": "C",
    "city": "Kota Blitar",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 37823
  },
  {
    "no": 75,
    "name": "RS Muhammadiyah Tuban",
    "email": "rsab_muh_tbn@ymail.com / rsabmtuban@gmail.com",
    "code": "3523052",
    "rsoName": "RS Muhammadiyah Tuban",
    "class": "D",
    "city": "Tuban",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 10801
  },
  {
    "no": 76,
    "name": "RSIA Muhammadiyah Malang",
    "email": "rsabm_mlg@yahoo.com",
    "code": "3573135",
    "rsoName": "RS Ibu dan Anak Muhammadiyah Malang",
    "class": "C",
    "city": "Kota Malang",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 2020
  },
  {
    "no": 77,
    "name": "RSU Islam ‘Aisyiyah Malang",
    "email": "rsiaisyiyah_malang@yahoo.com / rsiaisyiyah_malang@yahoo.co.id",
    "code": "3573215",
    "rsoName": "RS Umum Islam Aisyiyah Malang",
    "class": "C",
    "city": "Kota Malang",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 148500
  },
  {
    "no": 78,
    "name": "RS ‘Aisyiyah Bojonegoro",
    "email": "rsabgoro@gmail.com",
    "code": "3522025",
    "rsoName": "Rumah Sakit Aisyiyah Bojonegoro",
    "class": "C",
    "city": "Bojonegoro",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 48040
  },
  {
    "no": 79,
    "name": "RS Muhammadiyah Kalitidu Bojonegoro",
    "email": "rsmuhammadiyahkalitidu@gmail.com",
    "code": "3522060",
    "rsoName": "RS Muhammadiyah Kalitidu",
    "class": "D",
    "city": "Bojonegoro",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 12080
  },
  {
    "no": 80,
    "name": "RS Siti Khodijah Muhammadiyah Cabang Sepanjang",
    "email": "sekretariat.rssk@gmail.com",
    "code": "3515026",
    "rsoName": "RS Umum Siti Khodijah Muhammadiyah Cabang Sepanjan",
    "class": "B",
    "city": "Sidoarjo",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 140532
  },
  {
    "no": 81,
    "name": "RS ‘Aisyiyah Siti Fatimah Tulangan, Sidoarjo",
    "email": "aisyiyah.15@gmail.com",
    "code": "3515138",
    "rsoName": "RS Umum Aisyiyah Siti Fatimah",
    "class": "D",
    "city": "Sidoarjo",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 29748
  },
  {
    "no": 82,
    "name": "RS Muhammadiyah Lamongan",
    "email": "rsmlamongan@gmail.com / sekretariat@rsmlamongan.com",
    "code": "3524031",
    "rsoName": "RS Umum Muhammadiyah Lamongan",
    "class": "B",
    "city": "Lamongan",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 74905
  },
  {
    "no": 83,
    "name": "RS Muhammadiyah Babat",
    "email": "eresembe@gmail.com",
    "code": "3524047",
    "rsoName": "RS Muhammadiyah Babat",
    "class": "D",
    "city": "Lamongan",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 19052
  },
  {
    "no": 84,
    "name": "RSI Muhammadiyah Sumberrejo",
    "email": "rsimsumberrejo@yahoo.co.id",
    "code": "3522036",
    "rsoName": "RSI Muhammadiyah Sumberrejo",
    "class": "D",
    "city": "Bojonegoro",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 34617
  },
  {
    "no": 85,
    "name": "RSI Hasanah Muhammadiyah Mojokerto",
    "email": "rsihasanah@gmail.com / rsihasanah@yahoo.com",
    "code": "3576051",
    "rsoName": "RS Islam Hasanah Muhammadiyah",
    "class": "C",
    "city": "Kota Mojokerto",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 16993
  },
  {
    "no": 86,
    "name": "RSU ‘Aisyiyah Ponorogo",
    "email": "rsuapo@yahoo.co.id",
    "code": "3502112",
    "rsoName": "RS Umum Aisyiyah Ponorogo",
    "class": "C",
    "city": "Ponorogo",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 102878
  },
  {
    "no": 87,
    "name": "RSU Muhammadiyah Ponorogo",
    "email": "rsum_ponorogo@yahoo.com",
    "code": "3502134",
    "rsoName": "RS Umum Muhammadiyah Ponorogo",
    "class": "C",
    "city": "Ponorogo",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 78820
  },
  {
    "no": 88,
    "name": "RSU PKU Muhammadiyah Rogojampi",
    "email": "pkurogojampi@gmail.com",
    "code": "3510104",
    "rsoName": "RS Umum PKU Muhammadiyah Rogojampi",
    "class": "D",
    "city": "Banyuwangi",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 10509
  },
  {
    "no": 89,
    "name": "RS Islam Fatimah Banyuwangi",
    "email": "rsifatimah@gmail.com",
    "code": "3510054",
    "rsoName": "RS Islam Fatimah",
    "class": "C",
    "city": "Banyuwangi",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 16785
  },
  {
    "no": 90,
    "name": "RSIA Muhammadiyah Kota Probolinggo",
    "email": "rsabm_probolinggo@yahoo.com",
    "code": "3574069",
    "rsoName": "RS Ibu dan Anak Muhammadiyah Kota Probolinggo",
    "class": "C",
    "city": "Kota Probolinggo",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 7134
  },
  {
    "no": 91,
    "name": "RS Muhammadiyah Gresik",
    "email": "rsibmg@yahoo.com / rsabmg@yahoo.com",
    "code": "3525088",
    "rsoName": "RS Muhammadiyah Gresik",
    "class": "C",
    "city": "Gresik",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 23566
  },
  {
    "no": 92,
    "name": "RSU PKU Muhammadiyah Sekapuk",
    "email": "rs.pku.muhammadiyah@gmail.com",
    "code": "3525095",
    "rsoName": "RS PKU Muhammadiyah Sekapuk",
    "class": "D",
    "city": "Gresik",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 17734
  },
  {
    "no": 93,
    "name": "RS PKU Muhammadiyah Surabaya",
    "email": "rsm_sby@yahoo.com",
    "code": "3578793",
    "rsoName": "RS PKU Muhammadiyah Surabaya",
    "class": "D",
    "city": "Kota Surabaya",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 5226
  },
  {
    "no": 94,
    "name": "RS Islam ‘Aisyiyah Nganjuk",
    "email": "rsianganjuk@yahoo.com",
    "code": "3518046",
    "rsoName": "RS Islam Aisyiyah Nganjuk",
    "class": "D",
    "city": "Nganjuk",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 23089
  },
  {
    "no": 95,
    "name": "RSI Siti Aisyah Madiun",
    "email": "rsi_madiun@yahoo.co.id",
    "code": "3577074",
    "rsoName": "RS Umum Islam Siti Aisyah",
    "class": "C",
    "city": "Kota Madiun",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 79927
  },
  {
    "no": 96,
    "name": "RS Muhammadiyah Jombang",
    "email": "rumahsakitmuhammadiyahjombang@yahoo.com",
    "code": "3517092",
    "rsoName": "RS Muhammadiyah Jombang",
    "class": "D",
    "city": "Jombang",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 4799
  },
  {
    "no": 97,
    "name": "RS PKU Muhammadiyah Mojoagung Jombang",
    "email": "pkumuhammadiyahjmbg@yahoo.com / pkumuhammadiyahmjg@yahoo.co.id",
    "code": "3517109",
    "rsoName": "RS Umum PKU Muhammadiyah Mojoagung",
    "class": "D",
    "city": "Jombang",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 18937
  },
  {
    "no": 98,
    "name": "RSU Muhammadiyah Bandung Tulungagung",
    "email": "rsum_bandung@yahoo.co.id",
    "code": "3504071",
    "rsoName": "RS Umum Muhammadiyah Bandung",
    "class": "D",
    "city": "Tulungagung",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 33548
  },
  {
    "no": 99,
    "name": "RS Muhammadiyah Siti Khodijah Gurah-Kediri",
    "email": "rsm.sitikhodijah.kediri@gmail.com",
    "code": "3506059",
    "rsoName": "RS Muhammadiyah Siti Khodijah",
    "class": "D",
    "city": "Kediri",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 14217
  },
  {
    "no": 100,
    "name": "RSU Universitas Muhammadiyah Malang",
    "email": "rumahsakit.umm@gmail.com / hospital@umm.ac.id",
    "code": "3507108",
    "rsoName": "RS Umum Universitas Muhammadiyah Malang",
    "class": "C",
    "city": "Malang",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 115040
  },
  {
    "no": 101,
    "name": "RS Muhammadiyah Lumajang",
    "email": "rsum.lmj@gmail.com",
    "code": "3508060",
    "rsoName": "RS Umum Muhammadiyah Lumajang",
    "class": "D",
    "city": "Lumajang",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 10740
  },
  {
    "no": 102,
    "name": "RS Muhammadiyah Kali Kapas Lamongan",
    "email": "rsmkalikapas@gmail.com / rsmuhammadiyahkalikapas@gmail.com",
    "code": "3524056",
    "rsoName": "RS Muhammadiyah Kalikapas Lamongan",
    "class": "D",
    "city": "Lamongan",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 2583
  },
  {
    "no": 103,
    "name": "RSU Muhammadiyah Babat",
    "email": "rsumbabat@gmail.com",
    "code": "3524049",
    "rsoName": "RS Umum Muhammadiyah Babat",
    "class": "C",
    "city": "Lamongan",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 22592
  },
  {
    "no": 104,
    "name": "RSU Universitas Muhammadiyah Jember",
    "email": "rsuunmuhjember@unmuhjember.ac.id",
    "code": "3509151",
    "rsoName": "RS Umum Universitas Muhammadiyah Jember",
    "class": "C",
    "city": "Jember",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 13991
  },
  {
    "no": 105,
    "name": "RSIA Aisyiyah Bangkalan",
    "email": "aisyiyah.rsia@gmail.com",
    "code": "3526030",
    "rsoName": "RS Ibu dan Anak Aisyiyah",
    "class": "C",
    "city": "Bangkalan",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 864
  },
  {
    "no": 106,
    "name": "RSU Assakinah Medika",
    "email": "humasrsuamedika@gmail.com",
    "code": "3515127",
    "rsoName": "RS Umum Assakinah Medika",
    "class": "D",
    "city": "Sidoarjo",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 23369
  },
  {
    "no": 107,
    "name": "RS Moedjito Dwidjosiswojo",
    "email": "office.moedjito@gmail.com",
    "code": "3517091",
    "rsoName": "RS Umum dr. Moedjito Dwidjosiswojo",
    "class": "D",
    "city": "Jombang",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 8805
  },
  {
    "no": 108,
    "name": "RSIA Sekarwangi Magetan",
    "email": "rsia.sekarwangi@gmail.com",
    "code": "3520014",
    "rsoName": "RS Ibu dan Anak Sekar Wangi",
    "class": "C",
    "city": "Magetan",
    "prov": "JAWA TIMUR",
    "inOj": true,
    "cases": 465
  },
  {
    "no": 109,
    "name": "RS PKU Muhammadiyah Yogyakarta",
    "email": "pkujogja@yahoo.co.id / pkujogja@gmail.com",
    "code": "3471041",
    "rsoName": "RS PKU Muhammadiyah Yogyakarta",
    "class": "B",
    "city": "Kota Yogyakarta",
    "prov": "D I YOGYAKARTA",
    "inOj": true,
    "cases": 79386
  },
  {
    "no": 110,
    "name": "RSU PKU Muhammadiyah Bantul",
    "email": "pkubantul@gmail.com",
    "code": "3402031",
    "rsoName": "RSU PKU Muhammadiyah Bantul",
    "class": "C",
    "city": "Bantul",
    "prov": "D I YOGYAKARTA",
    "inOj": true,
    "cases": 119442
  },
  {
    "no": 111,
    "name": "RSKIA PKU Muhammadiyah Kotagede",
    "email": "pkukotagede@yahoo.co.id",
    "code": "3471107",
    "rsoName": "RS Khusus Ibu dan Anak  PKU Muhammadiyah Kotagede",
    "class": "C",
    "city": "Kota Yogyakarta",
    "prov": "D I YOGYAKARTA",
    "inOj": true,
    "cases": 2278
  },
  {
    "no": 112,
    "name": "RSU PKU Muhammadiyah Nanggulan",
    "email": "rs.pku.nanggulan@gmail.com",
    "code": "3401050",
    "rsoName": "RS Umum PKU Muhammadiyah Nanggulan",
    "class": "D",
    "city": "Kulon Progo",
    "prov": "D I YOGYAKARTA",
    "inOj": true,
    "cases": 9159
  },
  {
    "no": 113,
    "name": "RS PKU Muhammadiyah Gamping Yogyakarta",
    "email": "pku.gamping@gmail.com",
    "code": "3404183",
    "rsoName": "RS Umum PKU Muhammadiyah Gamping",
    "class": "B",
    "city": "Sleman",
    "prov": "D I YOGYAKARTA",
    "inOj": true,
    "cases": 118835
  },
  {
    "no": 114,
    "name": "RS PKU Muhammadiyah Wonosari",
    "email": "rspkuwonosari@yahoo.co.id",
    "code": "3403024",
    "rsoName": "RS Umum PKU Muhammadiyah Wonosari",
    "class": "D",
    "city": "Gunung Kidul",
    "prov": "D I YOGYAKARTA",
    "inOj": true,
    "cases": 21200
  },
  {
    "no": 115,
    "name": "RS Universitas Ahmad Dahlan Yogyakarta",
    "email": "info@rsuad.co.id / holistika.medika@gmail.com",
    "code": "3404191",
    "rsoName": "RS Universitas Ahmad Dahlan",
    "class": "D",
    "city": "Sleman",
    "prov": "D I YOGYAKARTA",
    "inOj": true,
    "cases": 42536
  },
  {
    "no": 116,
    "name": "RSGM Universitas Muhammadiyah Yogyakarta",
    "email": "rsgmp@umy.ac.id / rektorat@umy.ac.id",
    "code": "3471374",
    "rsoName": "RS Gigi dan Mulut Universitas Muhammadiyah Yogyakarta",
    "class": "A",
    "city": "Kota Yogyakarta",
    "prov": "D I YOGYAKARTA",
    "inOj": false,
    "cases": 0
  },
  {
    "no": 117,
    "name": "RS Asri Medical Centre",
    "email": "asrimedicalcenter@gmail.com",
    "code": "3471381",
    "rsoName": "RS AMC Muhammadiyah",
    "class": "D",
    "city": "Kota Yogyakarta",
    "prov": "D I YOGYAKARTA",
    "inOj": true,
    "cases": 49551
  },
  {
    "no": 118,
    "name": "RS PKU Muhammadiyah Sleman",
    "email": "rspkusleman@gmail.com",
    "code": "3404210",
    "rsoName": "RS PKU Muhammadiyah Sleman",
    "class": "C",
    "city": "Sleman",
    "prov": "D I YOGYAKARTA",
    "inOj": true,
    "cases": 18631
  },
  {
    "no": 119,
    "name": "RS PKU Muhammadiyah Bima",
    "email": "rspkubima@yahoo.co.id",
    "code": "5206028",
    "rsoName": "RS PKU Muhammadiyah Bima",
    "class": "D",
    "city": "Kota Bima",
    "prov": "NUSA TENGGARA BARAT",
    "inOj": true,
    "cases": 22269
  },
  {
    "no": 120,
    "name": "RS Surya Medika PKU Muhammadiyah Sumbawa",
    "email": "suryamedikahospital@umm.ac.id",
    "code": "5207004",
    "rsoName": "RS Abdul Malik Fadjar PKU Muhammadiyah Sumbawa",
    "class": "D",
    "city": "Sumbawa",
    "prov": "NUSA TENGGARA BARAT",
    "inOj": true,
    "cases": 12857
  },
  {
    "no": 121,
    "name": "RSI PKU Muhammadiyah Palangkaraya",
    "email": "rsipalangkaraya@yahoo.co.id",
    "code": "6271024",
    "rsoName": "RS Islam PKU Muhammadiyah Palangka Raya",
    "class": "C",
    "city": "Kota Palangka Raya",
    "prov": "KALIMANTAN TENGAH",
    "inOj": true,
    "cases": 8907
  },
  {
    "no": 122,
    "name": "RSIA ‘Aisyiyah Samarinda",
    "email": "rsiaa_smd@yahoo.com / rsiaaa_smd@yahoo.com",
    "code": "6472052",
    "rsoName": "RS Ibu dan Anak  Aisyiyah Samarinda",
    "class": "C",
    "city": "Kota Samarinda",
    "prov": "KALIMANTAN TIMUR",
    "inOj": true,
    "cases": 4494
  },
  {
    "no": 123,
    "name": "RS Islam Banjarmasin",
    "email": "rs_islambjm@yahoo.com",
    "code": "6371046",
    "rsoName": "RS Islam Banjarmasin",
    "class": "C",
    "city": "Kota Banjarmasin",
    "prov": "KALIMANTAN SELATAN",
    "inOj": true,
    "cases": 45983
  },
  {
    "no": 124,
    "name": "RSIA Sitti Khadijah I Muhammadiyah Cab.Makassar",
    "email": "rsia.sitti.khadijah@gmail.com",
    "code": "7371191",
    "rsoName": "RS Ibu dan Anak Sitti Khadijah 1 Muhammadiyah",
    "class": "C",
    "city": "Kota Makassar",
    "prov": "SULAWESI SELATAN",
    "inOj": true,
    "cases": 4830
  },
  {
    "no": 125,
    "name": "RS PKU Muhammadiyah Mamajang",
    "email": "rsiakhadijahmamajang@rocketmail.com / rsiakhadijahtigamamajang@gmail.com",
    "code": "7371400",
    "rsoName": "RS PKU Muhammadiyah Mamajang",
    "class": "D",
    "city": "Kota Makassar",
    "prov": "SULAWESI SELATAN",
    "inOj": true,
    "cases": 3820
  },
  {
    "no": 126,
    "name": "RS ‘Aisyiyah Siti Khadijah Pinrang",
    "email": "rsa.stkhadijah@yahoo.com",
    "code": "7315016",
    "rsoName": "RS Umum Aisyiyah St. Khadijah",
    "class": "D",
    "city": "Pinrang",
    "prov": "SULAWESI SELATAN",
    "inOj": true,
    "cases": 10150
  },
  {
    "no": 127,
    "name": "RS PKU Muhammadiyah Unismuh Makassar",
    "email": "sekretariat@rsunismuh.com",
    "code": "7306070",
    "rsoName": "RS PKU Muhammadiyah Unismuh Makassar",
    "class": "C",
    "city": "Gowa",
    "prov": "SULAWESI SELATAN",
    "inOj": true,
    "cases": 31096
  },
  {
    "no": 128,
    "name": "RSIA PKU Muhammadiyah Palu",
    "email": "sudirman.aulia@gmail.com",
    "code": "7271032",
    "rsoName": "-",
    "class": "-",
    "city": "-",
    "prov": "-",
    "inOj": false,
    "cases": 0
  },
  {
    "no": 129,
    "name": "RSIA Siti Khadijah Kota Gorontalo",
    "email": "rsia_gtlo@yahoo.co.id",
    "code": "7571022",
    "rsoName": "RS Ibu dan Anak Siti Khadidjah",
    "class": "C",
    "city": "Kota Gorontalo",
    "prov": "GORONTALO",
    "inOj": true,
    "cases": 5959
  },
  {
    "no": 130,
    "name": "RS Islam PKU Muhammadiyah Maluku Utara",
    "email": "rs_islam_ternate@yahoo.co.id",
    "code": "8271042",
    "rsoName": "RS Islam PKU Muhammadiyah Maluku Utara",
    "class": "D",
    "city": "Kota Ternate",
    "prov": "MALUKU UTARA",
    "inOj": true,
    "cases": 7528
  },
  {
    "no": 131,
    "name": "RS UMS AR Fachrudin",
    "email": "",
    "code": "3372255",
    "rsoName": "RS UMS AR FACHRUDIN",
    "class": "D",
    "city": "Kota Surakarta",
    "prov": "JAWA TENGAH",
    "inOj": false,
    "cases": 0
  }
];